### ISSUE TITLE
single reads and distal regions

### ISSUE THREAD

**Issue by ahorvath** [jianhong/ATACseqQC#11]
Hi,

I have two questions regarding ATACseqQC:

1. Can it be applied on single end bams?
2. Can the analysis be restricted to distal elements (provided as a bed file)?

Thanks in advance!

Best Regards,
Attila

**Comment by jianhong** [comment]
both answers are no.

Best!

Your sincerely,

Jianhong Ou

**Comment by ahorvath** [comment]
OK, thanks for your answers.

Best Regards,
Attila
