### ISSUE TITLE
inconsistencies between the package code and user guide

### ISSUE THREAD

**Issue by tinavisnovska** [jianhong/ATACseqQC#33]
Hi, 

1) In the guide's section 2.4.4 (Transcription Start Site (TSS) Enrichment Score): function `TSSEscore` returns `$TSSEscore` and `$values`, however, today's version of the function does not return them.

2) In the guide's section 2.5 (plot footprints): function `featureAlignedHeatmap` is used, while there is not such function available in the today's version of the package.

Anyway, thanks for providing the package!

**Comment by jianhong** [comment]
featureAlignedHeatmap is a function in ChIPpeakAnno. 
This inconsistence of package and vignette is caused by the lags of bioconductor building. It should fixed automatically once the bioconductor rebuild the package.
