### ISSUE TITLE
plot correlation is not symmetric

### ISSUE THREAD

**Issue by noorisotoudeh** [jianhong/ATACseqQC#35]
Hi Jianhong,
I used plotCorrelation to find out that which of the bam files is highly different from others but surprisingly the out put is not symmetric. I mean as the picture below shows for instance for input6-input5 there is two different colors (one of them is darker). can you please tell me what is wrong? 
thanks
Noori

  
![image](https://user-images.githubusercontent.com/62612418/96347222-3b2a3180-106e-11eb-92bc-d3c503c4cad4.png)

**Comment by jianhong** [comment]
Hi Noori,

Thank you for reporting that. The heatmap is rescaled by row. now I fixed this bug by remove the rescale.

Jianhong.
