### ISSUE TITLE
Processing multiple bam files at once

### ISSUE THREAD

**Issue by etiennedanis** [jianhong/ATACseqQC#43]
Hello,
Thank you very much for creating ATACseqQC!
It is a great tool!
I may have missed it but is there a way to process multiple bam files at once?
Thank you very much in advance for letting me know.
Best,
Etienne

**Comment by jianhong** [comment]
Hi Etienne,

Thank you for your good words. No, current versions can’t handle multiple bam files.

Best!

Your sincerely,

Jianhong Ou

**Comment by etiennedanis** [comment]
Thank you very much for letting me know, Jianhong!
I'll just do a for loop to go over all the bam files in my directory.

New questions for you (should I submit them as new questions/issues?):
To get the report of all the QC metrics with bamQC, it looks like I should use:
bamQC(bamFile, outPath = NULL)
To get the bam files cleaned up, it looks like I should use:
bamQC(bamfile,
index = bamfile,
mitochondria = "chrM",
outPath = sub(".bam", ".clean.bam", basename(bamfile)),
doubleCheckDup = FALSE)

1. Is there a way to get both the QC report and the clean up of the bam files?
2. Besides the reads with low alignment scores, the reads derived from mitochondrial DNA or PCR/optical duplicates, are there any other filters applied by bamQC?
3. What are the parameters used for removing the reads with low alignment scores? Is it only reads with a MAPQ score (samtools view -q 30) below 30 being removed? Any other reads are being removed?
Thank you very much in advance.

Cheers,
Etienne
