### ISSUE TITLE
What does the x axis mean for Nucleosome Free Regions (NFR) score plot?

### ISSUE THREAD

**Issue by hyjforesight** [jianhong/ATACseqQC#46]
Hello ATACseqQC,
Thanks for developing this amazing package.
Could you please tell me what's the meaning of the x axis of Nucleosome Free Regions (NFR) score plot? It says 'the average signals of **400 bp** window as X-axis', but the title of NFR score plot shows 'NFRscore for **200bp** flanking TSSs'.
![image](https://user-images.githubusercontent.com/75048821/153695542-fe7e994d-7faf-4eb1-b3a9-ad15cb1a8f91.png)
Thanks!
Best,
YJ

**Comment by jianhong** [comment]
Thank you for your good words. The 200bp in the plot title means upstream 200bp + downstream 200bp. Sorry for the confusion.

**Comment by hyjforesight** [comment]
Hello @jianhong 
Thanks for the response. Now I get it. Sorry, I'm also confused about the meaning of the values of x-axis. Are they the values of log2 mean coverage, not the distance (bp) to the TSS?

**Comment by jianhong** [comment]
Yes, they are log2 mean coverage.
