### ISSUE TITLE
Error in TSSEscore calculation

### ISSUE THREAD

**Issue by pai-vlc** [jianhong/ATACseqQC#56]
Thanks for developing this pipeline. I have run it successfully with the test file, but when I try with my ATAC-Seq data I am getting an error. 

#Transcription Start Site (TSS) Enrichment Score
tsse <- TSSEscore(gal1, txs)
Error in rbind(...) : 
  number of columns of matrices must match (see arg 27)

My data are from mouse cells, so I change all the libraries to the mm10 build.

Do you know what could have gone wrong?

Thanks

Pepe

**Comment by jianhong** [comment]
Thank you for reporting this. Could you please share me the minimal sample data to repeat your error?

Jianhong.

**Comment by pai-vlc** [comment]
Do you mean the original bam file? It's 4.2 Gb. Is there a way to downsample it? 

Or the shifted bam?

**Comment by jianhong** [comment]
The files with sample code for repeating the error. You can try to subset the bam file with samtools for example.
```
samtools view -bh -o tmp.bam ori.bam chr19
samtools view -bh -s 0.1 -o out.bam tmp.bam
rm tmp.bam
```

Hope this will help.

From: pai-vlc ***@***.***>
Date: Tuesday, July 11, 2023 at 12:02 PM
To: jianhong/ATACseqQC ***@***.***>
Cc: jianhong ou ***@***.***>, Comment ***@***.***>
Subject: Re: [jianhong/ATACseqQC] Error in TSSEscore calculation (Issue #56)

Do you mean the original bam file? It's 4.2 Gb. Is there a way to downsample it?

Or the shifted bam?

**Comment by pai-vlc** [comment]
I will try. Right now I get this error with that code
samtools view -bh -o tmp.bam ori.bam chr19
Error: unexpected symbol in "samtools view"
> I'm running this from Rstudio, if that makes a difference

**Comment by pai-vlc** [comment]
OK. I did it in the command line, and generated a bam.out file. How can I send it to you? I tried dropping it here, but it tells me it does not support this type of files

**Comment by pai-vlc** [comment]
the bam.out file is very small (8.5 Mb)

**Comment by jianhong** [comment]
Could you please first try to play with the bam file to repeat your error? And show me the code you tried and then try to send the bam file via email may OK in this small size. Thank you!

Jianhong

From: pai-vlc ***@***.***>
Date: Tuesday, July 11, 2023 at 1:37 PM
To: jianhong/ATACseqQC ***@***.***>
Cc: JIANHONG OU ***@***.***>, Comment ***@***.***>
Subject: Re: [jianhong/ATACseqQC] Error in TSSEscore calculation (Issue #56)

the bam.out file is very small (8.5 Mb)

**Comment by pai-vlc** [comment]
Interestingly, in the small subset bam file I made I do not get the error. I get the TSSEscore, no issues. 
What could be the difference?

**Comment by jianhong** [comment]
Then let figure out a method to share the raw bam file.

From: pai-vlc ***@***.***>
Date: Tuesday, July 11, 2023 at 2:51 PM
To: jianhong/ATACseqQC ***@***.***>
Cc: JIANHONG OU ***@***.***>, Comment ***@***.***>
Subject: Re: [jianhong/ATACseqQC] Error in TSSEscore calculation (Issue #56)

Interestingly, in the small subset bam file I made I do not get the error. I get the TSSEscore, no issues.
What could be the difference?

**Comment by pai-vlc** [comment]
I can put the bam file and my r script in a shared dropbox folder. What's a good email for you?

**Comment by pai-vlc** [comment]
actually, this is the link to the folder with those files.

https://www.dropbox.com/sh/96w90uvdbzcd05r/AAABWMKE8xVoAR6Y3c0_00_3a?dl=0

**Comment by jianhong** [comment]
I downloaded the files. You can remove the share links now.

Jianhong.

From: pai-vlc ***@***.***>
Date: Tuesday, July 11, 2023 at 3:23 PM
To: jianhong/ATACseqQC ***@***.***>
Cc: JIANHONG OU ***@***.***>, Comment ***@***.***>
Subject: Re: [jianhong/ATACseqQC] Error in TSSEscore calculation (Issue #56)

actually, this is the link to the folder with those files.

https://www.dropbox.com/sh/96w90uvdbzcd05r/AAABWMKE8xVoAR6Y3c0_00_3a?dl=0

**Comment by pai-vlc** [comment]
OK. Than you very much for taking the time to help with this.

**Comment by jianhong** [comment]
The issue should be fixed in the development version. Please try to install the devel version by 
```{r}
BiocManager::install("jianhong/ATACseqQC")
# check the version number
packageVersion("ATACseqQC") ## should be 1.25.1
```
Let me know if there is any issue.

**Comment by pai-vlc** [comment]
That has fixed the problem. Thanks again for your help!
